const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function build(browser) {
    const distDir = path.join(__dirname, `dist-${browser}`);

    // Creates the browser-specific target folder
    if (!fs.existsSync(distDir)) fs.mkdirSync(distDir);

    // Copy code assets into it from the src/ folder
    fs.copyFileSync('src/background.js', path.join(distDir, 'background.js'));
    fs.copyFileSync('src/drivers.js', path.join(distDir, 'drivers.js'));
    fs.copyFileSync('src/content.js', path.join(distDir, 'content.js'));
    fs.copyFileSync('src/util.js', path.join(distDir, 'util.js'));
    fs.copyFileSync('src/components.js', path.join(distDir, 'components.js'));
    fs.copyFileSync('src/styles.css', path.join(distDir, 'styles.css'));
    fs.copyFileSync('src/scraper.js', path.join(distDir, 'scraper.js'));
    fs.copyFileSync('src/requests.js', path.join(distDir, 'requests.js'));
    fs.copyFileSync('src/popup.html', path.join(distDir, 'popup.html'));
    fs.copyFileSync('src/popup.js', path.join(distDir, 'popup.js'));
    fs.copyFileSync('src/scraper_shopify.js', path.join(distDir, 'scraper_shopify.js'));
    fs.copyFileSync('src/scraper_utils.js', path.join(distDir, 'scraper_utils.js'));

    // Bundle styles.css into a JS string so it can be injected
    // synchronously into the shadow root — no fetch, no
    // web_accessible_resources dependency, no race condition.
    // const cardCss = fs.readFileSync('src/styles.css', 'utf8');
    // const cssBundle = `// AUTO-GENERATED by build.js — do not edit directly\nconst CARD_CSS = ${JSON.stringify(cardCss)};\n`;
    // fs.writeFileSync(path.join(distDir, 'css-bundle.js'), cssBundle);

    // Update asset copying to pull from src/
    fs.copyFileSync('src/default_logo.png', path.join(distDir, 'default_logo.png'));
    fs.copyFileSync('src/active_logo.png', path.join(distDir, 'active_logo.png'));

    // Rename and inject the correct manifest file from the root
    fs.copyFileSync(`manifest.${browser}.json`, path.join(distDir, 'manifest.json'));

    console.log(`✓ Built target for ${browser}`);

    // Regenerate the Xcode project from the fresh dist-safari output
    if (browser === 'safari') {
        try {
            execSync(
                `xcrun safari-web-extension-converter "${distDir}" --macos-only --bundle-identifier com.yourname.decidio --project-location "${path.join(__dirname, 'safari-project')}" --force --no-open`,
                { stdio: 'inherit' }
            );
            console.log('✓ Safari Xcode project regenerated');
        } catch (err) {
            console.error('✗ Safari converter failed:', err.message);
        }
    }
}

build('chrome');
build('safari');